### PR TITLE
Added dropdown components from Planner

### PR DESCRIPTION
**Pull request by christineramirez**
-Added single dates
-Added date range style

### CODE REVIEW

**Comment by christineramirez** [comment]
@melanieps1 - I'm going to merge and close this branch. Cool?

**Comment by christineramirez** [comment]
Actually, disregard that comment. I am going to remove the "Selected Date" button because we have no plans to ever include that in the date picker options. I'll let ya know when it's ready for merge.

**Comment by melanieps1** [comment]
All sounds good to me!

**Comment by christineramirez** [comment]
Ok sorry about that - DONE!

**Comment by christineramirez** [comment]
👍  from @melanieps1 on Slack. Merging...

**Pull request merged**
