### PR TITLE
Form fields

### PR DESCRIPTION
**Pull request by christineramirez**
This PR adds the following components and their states to our design library:
- Single-line text inputs (all sizes & material-style)
- Multi-line text areas (all sizes) **Note that material-style has been deprecated for use**
- Single-select inputs (all sizes & material-style)
- Date picker (single date and date range)
- Checkboxes (all sizes)
- Radio buttons (all sizes)

Other form fields that are in progress:
- Dropdowns (dropdownable component)
- Multi-select inputs

### CODE REVIEW

**Comment by melanieps1** [comment]
@christineramirez I'll just review it on my own - hopefully a thumbs up coming soon!

**Comment by melanieps1** [comment]
Okay @christineramirez here's my feedback:

- For text areas, I though we said they would be 100px+ tall during our Hackathon conversation?  The 40px just looks a little strange as the text isn't middle-aligned haha.

- The dropdown active and error states look a bit funky with the blue/red outlines around both the outside and to the left of the arrow.  Really small feedback and I'm pretty low on it, but just thought I'd bring it up if you wanted to take a second look.

- I'm a little confused about the text sizes, probably just because we haven't talked about it before.  It looks like size 12 font is becoming the default?  Historically, we have used size 14 everywhere - I'm a little worried about it being small for users, but if you're confident in it then I'm fine with the change, just wanted to know because that's an adjustment I'll have to make in designs going forward.

Thanks for getting this done, they are looking great!

**Comment by pk-nb** [comment]
Good point @melanieps1 — size 14px font is baked in most of our system and components. Would be a huge challenge to change—and I think it's better to opt on more accessible to our (potentially older) users

**Comment by pk-nb** [comment]
I'm still not sure about the error message that appears below form fields, particularly due to the fact that the component would jump in height (particularly sucky on modals). I don't know a good alternative but not sure if that was considered.

**Comment by melanieps1** [comment]
@pk-nb To your point about the error messages, Sarah expressed concern about that when I first showed her the pattern as well.  The jumpiness definitely isn't great.

One solution that I like but don't think it could solve for every use case is when there is a save/discard action at the end, just disabling that save button until all necessary fields are complete.

**Comment by mhuggins** [comment]
Is showing an error in a tooltip an option?

https://www.drupal.org/files/project-images/Screen%20Shot%202013-02-24%20at%201.43.59%20AM.png

**Comment by christineramirez** [comment]
I'll update to 14px.

We didn't really spend much time thinking about how we want to handle errors across the system. I do know that what's in the sketch file is how we currently handle errors (at least the examples I've seen in the Gallery modals. I can pull this error state from the Sketch library for now, if we agree those still need work (and add a note that this is in progress).

As far as disabling buttons to not allow our users to get into that state - we do, as a loose rule, try to do that. I'll update the spec to document that. But there will be cases that we need to address where that's not ideal. It could potentially be confusing especially when there are many fields. 

@mhuggins - all possible patterns for handling errors are fair game to evaluate.

**Comment by christineramirez** [comment]
For reference - here's how MD handles errors on form fields: https://material.google.com/patterns/errors.html#errors-user-input-errors

**Comment by pk-nb** [comment]
I think the MD pattern works really well because they kept the error text really small and the margins fit with it. That being said I don't know how user-friendly that is.

**Comment by christineramirez** [comment]
I think so too, we just haven't accommodated for that margin necessarily in our mocks, but we can moving forward. i'll play around with the sizing and the spacing and see what I come up with.

here's what i recommend if it all works out: in cases where there are ≤ 2 form fields, we disable the submit button. in cases where there are > 2 form fields, we use the error messages below each input making sure that the margins accommodate for the error messaging to appear without the shiftiness.

**Comment by melanieps1** [comment]
I like that solution!  Thanks for the discussion all and for working so hard on this Christine, this stuff is really exciting moving forward. :)

**Comment by christineramirez** [comment]
@melanieps1 and @pk-nb - 

I've addressed the following: 

- Updated font sizes for all components and updated the CRAFT library for Sketch
- Updated error state for inputs to include a light background for the inputs. *Note that the lightest red value that we have was too strong, so it's really error-red-lighten 4, 20% opacity.*
- Added footnote to address details around error handling 

Let me know your thoughts!

**Comment by melanieps1** [comment]
Looks good to me!  Great work @christineramirez 👍

**Comment by pk-nb** [comment]
Looks great! The only feedback I have is related to naming: the "optional" tags is actually a different component—the `MultiselectInput`. Don't know if you want to distinguish that as separate.

**Comment by christineramirez** [comment]
Yes, I'd like to be as precise as possible. Which artboard are you referring to, @pk-nb?

**Comment by pk-nb** [comment]
@christineramirez the Form Fields one

This pill section is under the TextInput doc, but it should probably be under it's own doc as a MultiselectInput (just like in shared UI). Looks like you already have a a doc for Single Select so might be good to mirror with multi.


screen shot 2016-09-07 at 2 22 04 pm

**Comment by christineramirez** [comment]
Ok i'll update

**Comment by christineramirez** [comment]
@pk-nb - done! will merge after your 👍

**Comment by pk-nb** [comment]
That was fast! Thanks! 👍

**Pull request merged**
