### PR TITLE
Small updates to App Components page

### PR DESCRIPTION
**Pull request by melanieps1**
- Made sure the App Components page was updated from any recent design
changes in the past few months
- Updated components that were affected by gray range changes
- Cleaned up layout a bit
- Updated the indeterminate checkbox to match what was developed in
shared-ui last week

### CODE REVIEW

**Comment by christineramirez** [comment]
This looks good - one minor thing I happened to notice is that the info icon size isn't rounded to a whole pixel. Somehow it's at 14.79 px. Can you update that please?

image

**Comment by melanieps1** [comment]
@christineramirez Updated - thanks.  Merging now!

**Comment by christineramirez** [comment]
thanks @mhuggins

**Comment by mhuggins** [comment]
Just being anal!

**Pull request merged**
